-- 0003_funnel — visitors, what they did, and the ones who left an email.
--
-- The funnel is measured rather than gated: content is free, email is optional,
-- and analytics is the growth instrument. That makes these three tables the
-- thing that has to work, and it makes their privacy posture load-bearing.
--
-- What is stored: a random first-party id, the referrer and UTM tags that
-- brought it in, a coarse country, a device class. What is NOT stored: an IP
-- address, a user agent string, or anything a third party sets. Anonymous
-- first-party measurement is legitimate interest; the email in `subscribers` is
-- marketing and carries an explicit consent flag.

create extension if not exists citext;

create type public.device_class as enum ('phone', 'tablet', 'desktop', 'other');

create table public.visitors (
  -- Generated by the browser and kept in a first-party cookie. It is not
  -- derived from anything about the person, so it identifies a browser rather
  -- than a human, and clearing site data genuinely resets it.
  anon_id      uuid primary key,
  first_seen   timestamptz not null default now(),
  last_seen    timestamptz not null default now(),
  referrer     text,
  utm_source   text,
  utm_medium   text,
  utm_campaign text,
  utm_content  text,
  utm_term     text,
  -- Country only. The IP it was derived from is never written down.
  country      text check (country is null or country ~ '^[A-Z]{2}$'),
  device       public.device_class
);

create index visitors_first_seen_idx on public.visitors (first_seen desc);
create index visitors_utm_source_idx on public.visitors (utm_source);

-- The event stream the funnel is computed from.
create table public.interactions (
  id           bigint generated always as identity primary key,
  anon_id      uuid references public.visitors(anon_id) on delete cascade,
  ts           timestamptz not null default now(),
  -- Free text rather than an enum: the kinds will grow with every block type,
  -- and a migration per new event kind is friction that ends with people
  -- overloading an existing one instead.
  kind         text not null check (length(btrim(kind)) > 0),
  report_slug  text,
  meta         jsonb not null default '{}'::jsonb
);

create index interactions_ts_idx on public.interactions (ts desc);
create index interactions_anon_idx on public.interactions (anon_id, ts desc);
create index interactions_report_idx on public.interactions (report_slug, kind, ts desc);

create table public.subscribers (
  id            uuid primary key default gen_random_uuid(),
  -- citext, so two people cannot sign up as the same address in different case.
  email         citext not null unique
                constraint subscribers_email_shape check (email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  created_at    timestamptz not null default now(),
  -- Which report produced this, and through which channel. The whole point of
  -- carrying the visitor id: a signup attributes back to the thing that earned it.
  source_report text,
  anon_id       uuid references public.visitors(anon_id) on delete set null,
  utm_source    text,
  utm_medium    text,
  utm_campaign  text,
  utm_content   text,
  utm_term      text,
  -- Marketing needs opt-in consent, and it is not a default.
  consent       boolean not null default false,
  verified      boolean not null default false,
  verified_at   timestamptz,
  unsubscribed_at timestamptz,

  constraint subscribers_verified_needs_a_time
    check (verified = false or verified_at is not null)
);

create index subscribers_created_idx on public.subscribers (created_at desc);
create index subscribers_anon_idx on public.subscribers (anon_id);
create index subscribers_report_idx on public.subscribers (source_report);

comment on table public.visitors is
  'One row per browser. First-party random id, no IP, no user agent, no third-party anything.';
comment on table public.interactions is
  'The funnel event stream. Anonymous readers may INSERT and may not SELECT.';
comment on table public.subscribers is
  'Optional email. Never a wall. consent is opt-in and defaults to false.';
